// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tfce
NumericMatrix tfce(NumericMatrix input_data, int chan_dim, IntegerMatrix ChN, NumericVector EH, int num_steps, bool has_negative, bool has_positive);
RcppExport SEXP _eegR_tfce(SEXP input_dataSEXP, SEXP chan_dimSEXP, SEXP ChNSEXP, SEXP EHSEXP, SEXP num_stepsSEXP, SEXP has_negativeSEXP, SEXP has_positiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type input_data(input_dataSEXP);
    Rcpp::traits::input_parameter< int >::type chan_dim(chan_dimSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ChN(ChNSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type EH(EHSEXP);
    Rcpp::traits::input_parameter< int >::type num_steps(num_stepsSEXP);
    Rcpp::traits::input_parameter< bool >::type has_negative(has_negativeSEXP);
    Rcpp::traits::input_parameter< bool >::type has_positive(has_positiveSEXP);
    rcpp_result_gen = Rcpp::wrap(tfce(input_data, chan_dim, ChN, EH, num_steps, has_negative, has_positive));
    return rcpp_result_gen;
END_RCPP
}
// consectrueRcpp
IntegerVector consectrueRcpp(LogicalMatrix x);
RcppExport SEXP _eegR_consectrueRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(consectrueRcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// rleRcpp
List rleRcpp(NumericMatrix x);
RcppExport SEXP _eegR_rleRcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rleRcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// charmatCollapse
CharacterVector charmatCollapse(CharacterMatrix x, int along_dim);
RcppExport SEXP _eegR_charmatCollapse(SEXP xSEXP, SEXP along_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type along_dim(along_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(charmatCollapse(x, along_dim));
    return rcpp_result_gen;
END_RCPP
}
// groupsum
NumericMatrix groupsum(NumericMatrix x, IntegerVector g, int ug);
RcppExport SEXP _eegR_groupsum(SEXP xSEXP, SEXP gSEXP, SEXP ugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type ug(ugSEXP);
    rcpp_result_gen = Rcpp::wrap(groupsum(x, g, ug));
    return rcpp_result_gen;
END_RCPP
}
// sweepcol_multitype_cpp
SEXP sweepcol_multitype_cpp(SEXP x, SEXP y, std::string fun);
RcppExport SEXP _eegR_sweepcol_multitype_cpp(SEXP xSEXP, SEXP ySEXP, SEXP funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type fun(funSEXP);
    rcpp_result_gen = Rcpp::wrap(sweepcol_multitype_cpp(x, y, fun));
    return rcpp_result_gen;
END_RCPP
}
// sweepcol_double_cpp
NumericMatrix sweepcol_double_cpp(NumericMatrix x, NumericVector y, std::string fun);
RcppExport SEXP _eegR_sweepcol_double_cpp(SEXP xSEXP, SEXP ySEXP, SEXP funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type fun(funSEXP);
    rcpp_result_gen = Rcpp::wrap(sweepcol_double_cpp(x, y, fun));
    return rcpp_result_gen;
END_RCPP
}
// sweepcol_logical_cpp
LogicalMatrix sweepcol_logical_cpp(SEXP x, SEXP y, std::string fun);
RcppExport SEXP _eegR_sweepcol_logical_cpp(SEXP xSEXP, SEXP ySEXP, SEXP funSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type fun(funSEXP);
    rcpp_result_gen = Rcpp::wrap(sweepcol_logical_cpp(x, y, fun));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eegR_tfce", (DL_FUNC) &_eegR_tfce, 7},
    {"_eegR_consectrueRcpp", (DL_FUNC) &_eegR_consectrueRcpp, 1},
    {"_eegR_rleRcpp", (DL_FUNC) &_eegR_rleRcpp, 1},
    {"_eegR_charmatCollapse", (DL_FUNC) &_eegR_charmatCollapse, 2},
    {"_eegR_groupsum", (DL_FUNC) &_eegR_groupsum, 3},
    {"_eegR_sweepcol_multitype_cpp", (DL_FUNC) &_eegR_sweepcol_multitype_cpp, 3},
    {"_eegR_sweepcol_double_cpp", (DL_FUNC) &_eegR_sweepcol_double_cpp, 3},
    {"_eegR_sweepcol_logical_cpp", (DL_FUNC) &_eegR_sweepcol_logical_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_eegR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
