# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tfce <- function(inData, chan_dim, ChN, EH, numSteps) {
    .Call('eegR_tfce', PACKAGE = 'eegR', inData, chan_dim, ChN, EH, numSteps)
}

consectrueRcpp <- function(x) {
    .Call('eegR_consectrueRcpp', PACKAGE = 'eegR', x)
}

rleRcpp <- function(x) {
    .Call('eegR_rleRcpp', PACKAGE = 'eegR', x)
}

